services:
  - type: web
    name: book-buddy-backend
    env: python
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application
    rootDir: backend
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-generated-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: book-buddy-backend-52jf.onrender.com
