services:
  - type: web
    name: book-buddy-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bookbuddy.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookbuddy.settings
      - key: PYTHON_VERSION
        value: 3.10
