# Generated by Django 5.2.3 on 2025-07-03 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
