# Generated by Django 5.2.3 on 2025-07-03 09:53

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_last_updated_book_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(default=books.models.today),
        ),
    ]
